services:
  pfsp:
    build:
      context: .
      dockerfile: Dockerfile

    image: pfsp-rk-grasp

    volumes:
      - ./PFSP_RK-GRASP/Results:/app/PFSP_RK-GRASP/Results
      - ./PFSP_RK-GRASP/Instances:/app/PFSP_RK-GRASP/Instances:ro

    command:
      - "../Instances/PFSP-tests-decoders.csv"
      - "3"
      - "0"